# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-02 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommender_id', models.IntegerField(blank=True, max_length=16, null=True)),
                ('login_name', models.CharField(max_length=32)),
                ('login_passwd', models.CharField(max_length=32)),
                ('status', models.CharField(default='0', max_length=8)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pause_date', models.DateTimeField(auto_now=True, null=True)),
                ('close_date', models.DateTimeField(auto_now=True, null=True)),
                ('real_name', models.CharField(max_length=32)),
                ('idcard_no', models.CharField(max_length=18)),
                ('birthdate', models.CharField(blank=True, max_length=18, null=True)),
                ('gender', models.CharField(blank=True, max_length=8, null=True)),
                ('occupation', models.CharField(blank=True, max_length=64, null=True)),
                ('telephone', models.CharField(max_length=18)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('mailaddress', models.CharField(blank=True, max_length=64, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=18, null=True)),
                ('qq', models.CharField(blank=True, max_length=18, null=True)),
                ('last_login_time', models.DateTimeField(auto_now=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'db_table': 'ACCOUNT',
            },
        ),
    ]
