# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-02 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='recommender_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=16),
        ),
    ]
