# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-31 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_duration', models.IntegerField()),
                ('base_cost', models.FloatField()),
                ('unit_cost', models.FloatField()),
                ('status', models.CharField(max_length=8)),
                ('descr', models.CharField(max_length=128)),
                ('creatime', models.DateTimeField(auto_now_add=True)),
                ('startime', models.DateTimeField(auto_now=True)),
                ('cost_type', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'cost',
            },
        ),
    ]
