# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-31 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='creatime',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='cost',
            name='startime',
            field=models.CharField(max_length=32),
        ),
    ]
