# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-31 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20190731_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='creatime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='startime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
