# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-31 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190731_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='status',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
