# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-05 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0002_auto_20190802_1119'),
        ('App', '0004_auto_20190731_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unix_host', models.CharField(max_length=16)),
                ('os_username', models.CharField(max_length=16)),
                ('login_passwd', models.CharField(max_length=16)),
                ('status', models.CharField(default='0', max_length=8)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('pause_date', models.CharField(max_length=32)),
                ('close_date', models.CharField(max_length=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Account')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Cost')),
            ],
            options={
                'db_table': 'SERVICE',
            },
        ),
    ]
