# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-05 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='create_data',
            new_name='create_date',
        ),
    ]
